apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: docker-eu-gcr-dev-website
spec:
  backendType: secretsManager
  region: {{ .Values.docker.secrets.region }}
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - key: {{ .Values.docker.secrets.name }}
      name: .dockerconfigjson
      property: dockerconfigjson
