docker:
  secrets:
    region: eu-west-1
    name: eu.gcr.io/dev-container-repo

replicaCount: 2

image:
  repository: eu.gcr.io/dev-container-repo/rola-website
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: docker-eu-gcr-dev-website

nameOverride: "rola-website"
fullnameOverride: "rola-website"

serviceAccount:
  create: true
  annotations: {}
  name: "rola-website"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9229

ingress:
  enabled: false
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  hosts: []

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

env: {}

secrets: []
