name: Release
on:
  push:
    branches:
      - develop
      - main
      - release/* 
    paths:
      - 'typescript/**'
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - name: Checkout
        uses: RDXWorks-actions/checkout@main
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: RDXWorks-actions/setup-node@main
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Prepare
        run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_TOKEN }}
        run: |
          npx semantic-release | tee out
          echo "RELEASE_VERSION=$(grep 'Created tag ' out | awk -F 'Created tag ' '{print $2}')" >> $GITHUB_ENV
